In [2]:
import numpy as np

In [7]:
# Criação de Arrays
x = np.array([[1,2,3,4], [2,3,4,5]])
print(x)
print(x.shape)

[[1 2 3 4]
 [2 3 4 5]]
(2, 4)


In [10]:
# Criação de array de zeros
dim = (4,10)
x = np.zeros(dim)
print(x)
print(x.shape)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
(4, 10)


In [11]:
# Criação de array de um
dim = (4,10)
x = np.ones(dim)
print(x)
print(x.shape)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
(4, 10)


In [33]:
# Criação do Array dentor de um intervalo 
# valores uniformes entre 5 e 20
x_min, x_max = 5, 20
x = np.linspace(x_min, x_max)
print(x)
print(x.shape)

[ 5.          5.30612245  5.6122449   5.91836735  6.2244898   6.53061224
  6.83673469  7.14285714  7.44897959  7.75510204  8.06122449  8.36734694
  8.67346939  8.97959184  9.28571429  9.59183673  9.89795918 10.20408163
 10.51020408 10.81632653 11.12244898 11.42857143 11.73469388 12.04081633
 12.34693878 12.65306122 12.95918367 13.26530612 13.57142857 13.87755102
 14.18367347 14.48979592 14.79591837 15.10204082 15.40816327 15.71428571
 16.02040816 16.32653061 16.63265306 16.93877551 17.24489796 17.55102041
 17.85714286 18.16326531 18.46938776 18.7755102  19.08163265 19.3877551
 19.69387755 20.        ]
(50,)


In [34]:
# Criação de Matriz Identidade
n = 4
x = np.eye(n)
print(x)
print(x.shape)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(4, 4)


In [38]:
# Criação de Matirz com valores aleatorios entre 0 e 1
x = np.random.random(size = (5,5))
print(x)
print(x.shape)

[[0.34478141 0.08134891 0.18271923 0.32025236 0.7899075 ]
 [0.64500019 0.32066054 0.59866289 0.30627361 0.38573338]
 [0.20130786 0.20351133 0.43725329 0.63179863 0.25503781]
 [0.34323956 0.70814339 0.07220304 0.84099622 0.10365337]
 [0.20002709 0.30662231 0.72545549 0.9534352  0.71109539]]
(5, 5)
